const { getDefaultConfig } = require('expo/metro-config')

const config = getDefaultConfig(__dirname)

// Allow Metro to import .sql migration files generated by drizzle-kit
config.resolver.sourceExts.push('sql')

module.exports = config
